### PR TITLE
Addition of Sound Effects and BG Music + Minor Improvements

### PR DESCRIPTION
**Pull request by Chris-1010**
- Added some music (created by Suno AI) to levels and menu
- Added sound effects for traversing the menu
- Added "Toggle Audio" option in settings
- Added previews of character sprites for character selection screen
- Tidy of formatting throughout project
- Removal of files which should not be version controlled
- Refactoring of `MenuState` and `GameState` variables into enums for greater readability
- Other minor improvements:
  - Added `.gitignore` file containing relevant files not to be included in version control
  - Moving to a different section of the menu resets the `menuCommandNum` back to 0
  - Selecting a character returns the user to the settings screen

### CODE REVIEW

**Comment by ex1tt** [comment]
Your code does not run. Problem with Font and Image

java.io.IOException: Problem reading font data.
        at java.desktop/java.awt.Font.createFont0(Font.java:1205)
        at java.desktop/java.awt.Font.createFont(Font.java:1076) 
        at ui.MenuUI.<init>(MenuUI.java:39)
        at ui.UIManager.<init>(UIManager.java:24)
        at main.Panel.loadMenu(Panel.java:99)
        at main.Panel.<init>(Panel.java:89)
        at main.Frame.<init>(Frame.java:14)
        at main.Main.main(Main.java:7)
java.io.IOException: Problem reading font data.
        at java.desktop/java.awt.Font.createFont0(Font.java:1205)
        at java.desktop/java.awt.Font.createFont(Font.java:1076)
        at ui.UIManager.<init>(UIManager.java:28)
        at main.Panel.loadMenu(Panel.java:99)
        at main.Panel.<init>(Panel.java:89)
        at main.Frame.<init>(Frame.java:14)
        at main.Main.main(Main.java:7)
Invalid high score format in file: For input string: ""
java.lang.NumberFormatException: For input string: ""
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:675)
        at java.base/java.lang.Integer.parseInt(Integer.java:781)
        at main.Panel.getHighScore(Panel.java:161)
        at main.Panel.loadMenu(Panel.java:103)
        at main.Panel.<init>(Panel.java:89)
        at main.Frame.<init>(Frame.java:14)
        at main.Main.main(Main.java:7)
Exception in thread "main" java.lang.IllegalArgumentException: input == null!
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1356)
        at main.UtilityTool.loadImage(UtilityTool.java:27)
        at entity.Player.setPlayerImage(Player.java:48)
        at entity.Player.<init>(Player.java:28)
        at main.Panel.loadMenu(Panel.java:107)
        at main.Panel.<init>(Panel.java:89)
        at main.Frame.<init>(Frame.java:14)
        at main.Main.main(Main.java:7)

**Comment by Chris-1010** [comment]
You're right that the code doesn't run out of the box - I apologize for that. While the main branch includes `.classpath` which makes it work immediately in Eclipse, relying on IDE configuration files in version control isn't considered best practice since they're IDE-specific and contain machine-specific paths. Instead, you can configure your IDE to properly setup the project.

> Your code does not run. Problem with Font and Image
> 
> java.io.IOException: Problem reading font data. at java.desktop/java.awt.Font.createFont0(Font.java:1205) at java.desktop/java.awt.Font.createFont(Font.java:1076) at ui.MenuUI.(MenuUI.java:39) at ui.UIManager.(UIManager.java:24) at main.Panel.loadMenu(Panel.java:99) at main.Panel.(Panel.java:89) at main.Frame.(Frame.java:14) at main.Main.main(Main.java:7) java.io.IOException: Problem reading font data. at java.desktop/java.awt.Font.createFont0(Font.java:1205) at java.desktop/java.awt.Font.createFont(Font.java:1076) at ui.UIManager.(UIManager.java:28) at main.Panel.loadMenu(Panel.java:99) at main.Panel.(Panel.java:89) at main.Frame.(Frame.java:14) at main.Main.main(Main.java:7) Invalid high score format in file: For input string: "" java.lang.NumberFormatException: For input string: "" at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) at java.base/java.lang.Integer.parseInt(Integer.java:675) at java.base/java.lang.Integer.parseInt(Integer.java:781) at main.Panel.getHighScore(Panel.java:161) at main.Panel.loadMenu(Panel.java:103) at main.Panel.(Panel.java:89) at main.Frame.(Frame.java:14) at main.Main.main(Main.java:7) Exception in thread "main" java.lang.IllegalArgumentException: input == null! at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1356) at main.UtilityTool.loadImage(UtilityTool.java:27) at entity.Player.setPlayerImage(Player.java:48) at entity.Player.(Player.java:28) at main.Panel.loadMenu(Panel.java:107) at main.Panel.(Panel.java:89) at main.Frame.(Frame.java:14) at main.Main.main(Main.java:7)

**Comment by ex1tt** [comment]
Right the classpath, project and bin in the main branch are an oversight on my part. I compiled and ran the code on both vscode and eclipse, seemed to have a problem locating font and images files. Probably missing a json config file or something to specify source and output paths, I will attempt again tomorrow.

**Comment by ex1tt** [comment]
Got it working, nice improvements!

**Pull request merged**
